export { About } from 'pages/about/About'
export { Fetch } from 'pages/fetch/Fetch'
export { Home } from 'pages/home/Home'
export { Login } from 'pages/login/Login'
export { NotFound } from 'pages/not-found/NotFound'
